source 'https://rubygems.org'

# Standard Rails gems
gem 'rails', '~> 4.1.7'
gem 'jquery-rails', '~> 3.1.2'
gem 'jbuilder', '~> 2.2.4'
gem 'bcrypt', '~> 3.1.9'
gem 'devise', '~> 3.4.1'
gem 'sqlite3', '~> 1.3.10'

group :assets do
  gem 'therubyracer'
  gem 'sass-rails'
  gem 'uglifier'
end